### ISSUE TITLE
Issue 5 - User can search their entries.

### ISSUE THREAD

**Issue by ry-zhao** [ry-zhao/code-journal#10]
## 💰 Motivation

User can search their entries. Provide a search box that causes the entries list to only show matches.

## 📐 Plan

Allow users to search entries from search box in the header.

## ✅ Task List

- [x] Create search box in the header.
- [x] Create search button to the right of the search box.
- [x] Add an event listener to the search button.
- [x] Create a callback function that finds all entries with title or notes content that matches the search String and creates and appends DOM trees representing matching entries to the entries view.
- [x] Remove extraneous CSS.
- [x] Test functionality again in private browsing session.
- [x] Fix all errors.
